return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "intelephense",
        "php-debug-adapter",
        "blade-formatter",
        "actionlint",
        "bash-language-server",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dot-language-server",
        "html-lsp",
        "nginx-language-server",
        "prettierd",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "biome",
        "js-debug-adapter",
        "vtsls",
        "yamlfmt",
        "jq",
        "sqlfmt",
      },
    },
  },
  { "williamboman/mason-lspconfig.nvim" },
  { "neovim/nvim-lspconfig" },
}
